Use command handler to handle deploy command failed
canonical/iot-auto-sanity pull request #16
Opened 2023-11-27 05:53 UTC by kiya956

impact:
    sanity/agent/agent.py
    sanity/agent/deploy.py

description:
    reduce duplicate code.

test:
    N/A

2023-11-27 06:29 UTC, tsunghanliu reviewed
one question about removing `send_mail()` entirely

2023-11-27 06:29 UTC, tsunghanliu commented on sanity/agent/deploy.py
> -                )
Can `send_mail()` in `init_mode_login()` be removed as well? Then we can remove `from sanity.agent.mail import mail` from `deploy.py`.

2023-11-27 06:42 UTC, kiya956 commented on sanity/agent/deploy.py
> -                )
in here we have two different case, one is init to login timeout, another is get serial assertion timeout. so if we remove the send_mail here, we need more return value to know what is the failed case

2023-11-28 01:55 UTC, tsunghanliu requested changes
LGTM, but two nitpicks.

2023-11-28 01:55 UTC, tsunghanliu commented on sanity/agent/agent.py
>                      print(gen_head_string("deploy procedure"))
guess this prompt should be printed before `status = deploy(...)`

2023-11-28 01:55 UTC, tsunghanliu commented on sanity/agent/deploy.py
> +            " Initial Device timeout: connect to store timeout",
Is the space here in purpose?

2023-11-28 02:36 UTC, tsunghanliu commented on sanity/agent/deploy.py
> +            " Initial Device timeout: connect to store timeout",
It's used to separate these two sentences.

2023-11-28 02:38 UTC, tsunghanliu commented on sanity/agent/deploy.py
> -                )
the new commit rewrite the usage of `send_mail()`

2023-11-28 03:52 UTC, kiya956 commented on sanity/agent/agent.py
>                      print(gen_head_string("deploy procedure"))
yes, thanks. Just update the PR

2023-12-07 00:31 UTC, tsunghanliu approved these changes
LGTM

2023-12-07 00:31 UTC, merged